# Start with a base image containing Java runtime
FROM openjdk:17-jdk-slim as build

# Add Maintainer Info
LABEL maintainer="ss.sharma1826@gmail.com"

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Set the location of the app
WORKDIR /app

# Copy the Maven Wrapper and pom.xml
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Fetch all dependencies
RUN ./mvnw dependency:go-offline -B

# Copy your application code (keeping the .m2 directory for caching)
COPY src src

# Build the application
RUN ./mvnw package -DskipTests

# Run the Spring Boot app using a script generated by the spring-boot-maven-plugin
FROM openjdk:17-jdk-slim
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
