# @format

apiVersion: v1
kind: Service
metadata:
  name: air-distance-backend-service
spec:
  type: LoadBalancer
  selector:
    app: air-distance-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
